[colors.primary]
background = "0x263238"
foreground = "0xeaeaea"

[cursor]
style = "Block"
unfocused_hollow = true

[env]
SHELL = "/opt/homebrew/bin/fish"

[font]
size = 15.5

[font.normal]
family = "DejaVuSansM Nerd Font"
style = "Regular"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Command"

# NOTE: at the moment tabs will only work when window.decorations = "Full"
# See https://github.com/alacritty/alacritty/issues/7626

[[keyboard.bindings]]
action = "CreateNewTab"
key = "T"
mods = "Command"

[[keyboard.bindings]]
action = "SelectTab1"
key = "1"
mods = "Command"

[[keyboard.bindings]]
action = "SelectTab2"
key = "2"
mods = "Command"

[[keyboard.bindings]]
action = "SelectTab3"
key = "3"
mods = "Command"

[mouse]
hide_when_typing = true

[shell]
args = ["-l", "-c", "tmux has-session && fish || tmux"]
program = "/opt/homebrew/bin/fish"

[window]
decorations = "Full"
# decorations = "Buttonless"
opacity = 0.95
blur = true
startup_mode = "Maximized"
decorations_theme_variant = "Dark"

[window.padding]
x = 5
y = 1
