#!/bin/bash
#
# This script shuts down the machine after a period of inactivity when there are no users logged in.
# It should be ran as a root cron job every ~10 minutes.
#
# NOTE: detached tmux/screen sessions count as logged-in users, so this will never shutdown
# a machine when there is a tmux or screen session running.
#
# To install this script, run the following:
#
# ```
# sudo wget https://raw.githubusercontent.com/epwalsh/dotfiles/master/shutdown-if-inactive -O /usr/bin/shutdown-if-inactive
# sudo chmod +x /usr/bin/shutdown-if-inactive
# ```
#
# Then run:
#
# ```
# sudo crontab -e
# ```
#
# And add the following line to the end of the file:
#
# ```
# */10 * * * * /usr/bin/shutdown-if-inactive 2>&1 > /var/log/shutdown-if-inactive.log
# ```
#
# If this script isn't working properly, check the logs: /var/log/shutdown-if-inactive.log

set -o nounset -o errexit -o pipefail

echo "Starting check at $(date)"

MARKER_FILE="/tmp/user-inactivity-flag"

LOGGED_IN=$(users)

if [ -n "$LOGGED_IN" ]; then
  # Delete marker file if it exists
  echo "Found users logged in, removing marker file"
  rm --force "$MARKER_FILE"
else
  if [ -f "$MARKER_FILE" ]; then
    echo "No users logged in, powering off"
    /usr/sbin/poweroff  # See https://unix.stackexchange.com/a/196014/56711
  else
    # Create a marker file so that it will shut down if still inactive on the next time this script runs.
    echo "No users logged in, creating marker file"
    touch "$MARKER_FILE"
  fi
fi
