format = """\
    $username\
    $hostname\
    $directory\
    $git_branch\
    $git_commit\
    $git_state\
    $git_status\
    $cmd_duration\
    $line_break\
    $package\
    $rust\
    $python\
    $line_break\
    $character\
    """
